import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Missing Supabase environment variables!')
  console.error('VITE_SUPABASE_URL:', supabaseUrl ? '✓' : '✗')
  console.error('VITE_SUPABASE_ANON_KEY:', supabaseAnonKey ? '✓' : '✗')
}

export const supabase = createClient(
  supabaseUrl || 'https://placeholder.supabase.co',
  supabaseAnonKey || 'placeholder-key'
)


/*
DB SCHEMA: 

create table public."Attendees" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  event_id bigint null,
  user_id uuid null,
  constraint Attendees_pkey primary key (id),
  constraint Attendees_event_id_fkey foreign KEY (event_id) references "Events" (id),
  constraint Attendees_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

create table public."Events" (
  id bigint generated by default as identity not null,
  description text null,
  name text null,
  location_lat double precision null,
  location_long double precision null,
  location_name text null,
  type text null,
  club_name text null,
  created_at timestamp with time zone not null default now(),
  time timestamp without time zone null,
  capacity integer null,
  club_url text null,
  owner_user uuid null,
  constraint Events_pkey primary key (id),
  constraint Events_owner_user_fkey foreign KEY (owner_user) references auth.users (id)
) TABLESPACE pg_default;

*/
